### ISSUE TITLE
tensorflow 1.2 AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by c1a1o1** [Tandon-A/Image-Editing-using-GAN#1]
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

**Comment by Tandon-A** [comment]
I have used Tensorflow 1.6 to develop this. I will update the Readme file. To resolve this issue for earlier versions, you can create a leaky relu function on your own.

**Comment by c1a1o1** [comment]
Thank you very much!
